project_id = "dnbbxsfgmscmbfsfyipk"

[functions.groot-chat]
verify_jwt = false

[functions.weather]
verify_jwt = false

[functions.analyze-plant-health]
verify_jwt = false

[functions.esp32-plant-analysis]
verify_jwt = false